# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dm_lm_bvs <- function(iterations, thin, alpha, y, z, x, phi, psi, temp_cc, temp_uu, sigma2_alpha, zeta, xi, sigma2_phi, a, b, a_0, b_0, h_alpha, h_beta, a_m, b_m) {
    .Call(`_DMLMbvs_dm_lm_bvs`, iterations, thin, alpha, y, z, x, phi, psi, temp_cc, temp_uu, sigma2_alpha, zeta, xi, sigma2_phi, a, b, a_0, b_0, h_alpha, h_beta, a_m, b_m)
}

ilr_fun_cpp <- function(x) {
    .Call(`_DMLMbvs_ilr_fun_cpp`, x)
}

log_post <- function(iterations, alpha, y, z, x, phi, psi, sigma2_alpha, zeta, xi, sigma2_phi, a, b, a_0, b_0, h_alpha, h_beta, a_m, b_m) {
    .Call(`_DMLMbvs_log_post`, iterations, alpha, y, z, x, phi, psi, sigma2_alpha, zeta, xi, sigma2_phi, a, b, a_0, b_0, h_alpha, h_beta, a_m, b_m)
}

loo_prep <- function(y, psi, xi, a_0, b_0, h_alpha, h_beta) {
    .Call(`_DMLMbvs_loo_prep`, y, psi, xi, a_0, b_0, h_alpha, h_beta)
}

log_zeta_pj_cpp <- function(t_pj, a, b) {
    .Call(`_DMLMbvs_log_zeta_pj_cpp`, t_pj, a, b)
}

